### ISSUE TITLE
Folders & Devices Screen stays empty

### ISSUE THREAD

**Issue by yeus** [syncthing/syncthing-lite#98]
I have a Huawei P Smart and Android 8.0.0.

The "folders" and "devices" screen stays empty. Also, the app crashes when I add a new device after putting in the ID.

I am pretty unexperienced regarding android is there any way I can help to debug this?

**Comment by Nutomic** [comment]
Did you download the app from Google Play, and send the crash report? That would be the easiest way to get the log.

**Comment by Pazuu** [comment]
Same here, just send the crash report. I think this is new since 0.3.4. thank you!!

**Comment by Pazuu** [comment]
I dont know whether this is important or not, but if i add a device the app crashes and there is no popup asking me to send a report via google play. But if i use the option to clear the index and cache the app crashes and i can send a report via google play (what i did).

**Comment by Nutomic** [comment]
@Pazuu No idea why that happens.

@l-jonas I think this is the correct crash report from Google Play. I can also give you access so you can view the reports yourself.
```
  at net.syncthing.lite.activities.IntroActivity$IntroFragmentTwo.isDeviceIdValid (IntroActivity.java:124)
  at net.syncthing.lite.activities.IntroActivity$onCreate$1.onClick (IntroActivity.java:46)
  at android.view.View.performClick (View.java:5201)
  at android.view.View$PerformClick.run (View.java:21209)
  at android.os.Handler.handleCallback (Handler.java:739)
  at android.os.Handler.dispatchMessage (Handler.java:95)
  at android.os.Looper.loop (Looper.java:148)
  at android.app.ActivityThread.main (ActivityThread.java:5525)
  at java.lang.reflect.Method.invoke (Method.java)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:730)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:620)
```

**Comment by l-jonas** [comment]
@Pazuu Does the crash happen in the setup wizard or when adding devices later in the App? (Or is it at both?) (the crash report above is for the setup wizard and looks like it's caused by a configuration change (screen rotation))

@Nutomic For the crash report access: Can I send you my google account id using the mail address which is at the bottom of <https://nutomic.com/>?

**Comment by Pazuu** [comment]
The crash happens after adding a device later (not in the wizard), as soon as this device (e.g. a laptop) accepts the syncthing lite smartphone and starts to establish a connection.

**Comment by l-jonas** [comment]
@Pazuu If you reset the App and add the device which you now added later as the first device, does it occur again then (or only if you later add the device which you now added as first device)? Is there really no way to send a crash report for this/ did you download the App from Google Play?

**Comment by l-jonas** [comment]
@Pazuu This sounds like your issue should be fixed with <https://github.com/syncthing/syncthing-lite/pull/91> (which is not yet part of a released version). Moreover, I created <https://github.com/syncthing/syncthing-lite/issues/102> because there could be other cases when crash reports are needed without relying on Google.

**Comment by Nutomic** [comment]
@l-jonas Yes, that would be perfect.

**Comment by Pazuu** [comment]
I am sorry, but i still experience the same crash with version 3.5 and i "turned on" the new built in Custom Crash-Handler, but it does not copy a log to the clipboard after this particular crash. After adding a device, the device view stays empty and the app crashes, as soon as the device accepts the syncthing lite smartphone and connects.

**Comment by Pazuu** [comment]
I am absolutly happy to wait and i really appreciate the work that is done here! Thank you!! :)

**Comment by Newar417** [comment]
Same here, as above. Additionally the "Show device ID", also stays blank (just circling until crash). 

0.3.5 from FDroid, Asus Z00A, Lineage OS 7.1.2

**Comment by l-jonas** [comment]
@Newar417 

> Additionally the "Show device ID", also stays blank (just circling until crash).

Which above (there are different described situations)? Did you add an device already or did you not add one? Can you provide a crash report (eventually the crash handler from the settings of the App itself works for you; otherwise: "adb logcat" should work always)?

**Comment by Newar417** [comment]
As in the first post. I have had a device added already. Two now in the meanwhile. The in-built crash reporter does not work for me. 

I hope this helps: 

`12-03 23:55:31.822   629 23464 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=net.syncthing.lite/.activities.MainActivity (has extras)} from uid 10030 on display 0
12-03 23:55:31.900   629  1633 I ActivityManager: Start proc 14197:net.syncthing.lite/u0a186 for activity net.syncthing.lite/.activities.MainActivity
12-03 23:55:31.924   629   629 D ZenLog  : intercepted: 0|android|17039403|null|1000,alarmsOnly
12-03 23:55:31.925   629   629 V NotificationService: pkg=android canInterrupt=false intercept=true
12-03 23:55:31.929 14197 14197 I art     : Starting a blocking GC AddRemoveAppImageSpace
12-03 23:55:31.930 14197 14197 W System  : ClassLoader referenced unknown path: /data/app/net.syncthing.lite-1/lib/x86
12-03 23:55:31.955 14197 14197 D SyncthingProvider: onCreate()
12-03 23:55:32.153 14197 14218 I OpenGLRenderer: Initialized EGL, version 1.4
12-03 23:55:32.153 14197 14218 D OpenGLRenderer: Swap behavior 1
12-03 23:55:32.154 14197 14218 W OpenGLRenderer: Failed to choose config with EGL_SWAP_BEHAVIOR_PRESERVED, retrying without...
12-03 23:55:32.154 14197 14218 D OpenGLRenderer: Swap behavior 0
12-03 23:55:32.205 14197 14221 D NetworkSecurityConfig: No Network Security Config specified, using platform default
12-03 23:55:32.216 14197 14197 E RecyclerView: No adapter attached; skipping layout
12-03 23:55:32.244 14197 14221 W System  : ClassLoader referenced unknown path: /system/framework/tcmclient.jar
12-03 23:55:32.267 14197 14227 I net.syncthing.a.d.d: received device address list from local discovery
12-03 23:55:32.426   629   651 I ActivityManager: Displayed net.syncthing.lite/.activities.MainActivity: +577ms
12-03 23:55:32.539 14197 14239 W System.err: java.lang.IllegalStateException: Module with the Main dispatcher is missing. Add dependency providing the Main dispatcher, e.g. 'kotlinx-coroutines-android'
12-03 23:55:32.539 14197 14239 W System.err: 	at kotlinx.coroutines.cc.a(Dispatchers.kt:123)
12-03 23:55:32.539 14197 14239 W System.err: 	at kotlinx.coroutines.cc.a(Dispatchers.kt:116)
12-03 23:55:32.539 14197 14239 W System.err: 	at kotlinx.coroutines.ay.a(Dispatched.kt:279)
12-03 23:55:32.539 14197 14239 W System.err: 	at kotlinx.coroutines.c.a.a(Cancellable.kt:23)
12-03 23:55:32.539 14197 14239 W System.err: 	at kotlinx.coroutines.al.a(CoroutineStart.kt:109)
12-03 23:55:32.539 14197 14239 W System.err: 	at kotlinx.coroutines.c.a(AbstractCoroutine.kt:160)
12-03 23:55:32.539 14197 14239 W System.err: 	at kotlinx.coroutines.i.a(Builders.common.kt:54)
12-03 23:55:32.539 14197 14239 W System.err: 	at kotlinx.coroutines.g.b(Unknown Source)
12-03 23:55:32.539 14197 14239 W System.err: 	at kotlinx.coroutines.i.a(Builders.common.kt:47)
12-03 23:55:32.539 14197 14239 W System.err: 	at kotlinx.coroutines.g.b(Unknown Source)
12-03 23:55:32.539 14197 14239 W System.err: 	at net.syncthing.lite.c.b$b.a(FoldersFragment.kt:43)
12-03 23:55:32.540 14197 14239 W System.err: 	at net.syncthing.lite.c.b$b.a(FoldersFragment.kt:20)
12-03 23:55:32.540 14197 14239 W System.err: 	at net.syncthing.lite.library.e$c.a(LibraryHandler.kt:130)
12-03 23:55:32.540 14197 14239 W System.err: 	at net.syncthing.lite.library.e$c.a(LibraryHandler.kt:28)
12-03 23:55:32.540 14197 14239 W System.err: 	at net.syncthing.lite.library.e$e$1.a(LibraryHandler.kt:113)
12-03 23:55:32.540 14197 14239 W System.err: 	at net.syncthing.lite.library.e$e$1.a(LibraryHandler.kt:28)
12-03 23:55:32.540 14197 14239 W System.err: 	at org.c.a.c$b.b(Async.kt:143)
12-03 23:55:32.540 14197 14239 W System.err: 	at org.c.a.c$b.a(Async.kt)
12-03 23:55:32.540 14197 14239 W System.err: 	at org.c.a.d.call(Async.kt)
12-03 23:55:32.540 14197 14239 W System.err: 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
12-03 23:55:32.540 14197 14239 W System.err: 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
12-03 23:55:32.540 14197 14239 W System.err: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
12-03 23:55:32.540 14197 14239 W System.err: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
12-03 23:55:32.540 14197 14239 W System.err: 	at java.lang.Thread.run(Thread.java:761)
12-03 23:55:33.171  5122 11765 W WebSocketConnection: Sending keep alive...
12-03 23:55:33.176  5122 11765 W RealtimeSleepTimer: Setting alarm to wake up in 55000ms.
12-03 23:55:33.269 13361 13508 D AppMonet/BidManager: syncing bidmanager with pool
12-03 23:55:33.269 13361 13508 D AppMonet/PubSubService: Message Topic -> cleanUpBids
12-03 23:55:33.456 14197 14234 I net.syncthing.a.c.d.a$c: keystore ready, device id = DeviceId(deviceId=CHANGED-CHANGED-CHANGED-CHANGED-CHANGED-CHANGED-CHANGED-CHANGED)
12-03 23:55:33.566  6373  6373 D wpa_supplicant: wlan0: Control interface command 'SIGNAL_POLL'
12-03 23:55:33.694 14197 14226 I net.syncthing.a.a.a.k: Received hello message, deviceName=fff, clientName=syncthing, clientVersion=v0.14.52
12-03 23:55:33.695 14197 14241 I System.out: writing config to /data/user/0/net.syncthing.lite/files/config.json
12-03 23:55:33.710 14197 14227 I net.syncthing.a.a.a.c: send delta index info device = EDITED-EDITED-EDITED-EDITED-EDITED-EDITED-EDITED-EDITED index = 8028699021205081617 max (local) sequence = 5184
12-03 23:55:33.715 14197 14227 I net.syncthing.a.a.a.c: send delta index info device = EDITED-EDITED-EDITED-EDITED-EDITED-EDITED-EDITED-EDITED index = -9188244080785029695 max (local) sequence = 3367
12-03 23:55:33.799 14197 14226 I net.syncthing.a.a.a.c: folder shared from device = DeviceId(deviceId=EDITED-EDITED-EDITED-EDITED-EDITED-EDITED-EDITED-EDITED) folder = ClusterConfigFolderInfo(folderId=hrmvq-odie5, label=Sync, isAnnounced=true, isShared=true)
12-03 23:55:33.801 14197 14202 I art     : Do partial code cache collection, code=30KB, data=23KB
12-03 23:55:33.802 14197 14202 I art     : After code cache collection, code=29KB, data=22KB
12-03 23:55:33.802 14197 14202 I art     : Increasing code cache capacity to 128KB
12-03 23:55:33.811 14197 14226 I net.syncthing.a.a.a.c: folder shared from device = DeviceId(deviceId=EDITED-EDITED-EDITED-EDITED-EDITED-EDITED-EDITED-EDITED) folder = ClusterConfigFolderInfo(folderId=jsrlr-nwpds, label=DCIM, isAnnounced=true, isShared=true)
12-03 23:55:33.823 14197 14226 I net.syncthing.a.a.a.c: folder shared from device = DeviceId(deviceId=EDITED-EDITED-EDITED-EDITED-EDITED-EDITED-EDITED-EDITED) folder = ClusterConfigFolderInfo(folderId=abc-photos, label=Camera, isAnnounced=true, isShared=true)
12-03 23:55:34.234 14197 14202 I art     : Do partial code cache collection, code=61KB, data=40KB
12-03 23:55:34.234 14197 14202 I art     : After code cache collection, code=59KB, data=39KB
12-03 23:55:34.234 14197 14202 I art     : Increasing code cache capacity to 256KB
12-03 23:55:34.252 14197 14225 I net.syncthing.a.a.h: received index message event, preparing (queued records = 0 event record count = 475)
12-03 23:55:34.256 14197 14244 I net.syncthing.a.a.h: processing index message with 475 records (queue size: messages = 1 records = 475)
12-03 23:55:34.392 14197 14225 I net.syncthing.a.a.h: received index message event, preparing (queued records = 475 event record count = 74)
12-03 23:55:34.557 14197 14225 I net.syncthing.a.a.h: received index message event, preparing (queued records = 549 event record count = 108)
12-03 23:55:34.975 14197 14225 I net.syncthing.a.a.h: received index message event, preparing (queued records = 657 event record count = 36)
12-03 23:55:35.187 14197 14225 I net.syncthing.a.a.h: received index message event, preparing (queued records = 693 event record count = 40)
12-03 23:55:35.570 14197 14225 I net.syncthing.a.a.h: received index message event, preparing (queued records = 733 event record count = 19)
12-03 23:55:35.722  5122 11746 W WebSocketConnection: WSC onMessage()
12-03 23:55:35.722  5122 11746 W WebSocketConnection: Message Type: 2
12-03 23:55:35.806 14197 14225 I net.syncthing.a.a.h: received index message event, preparing (queued records = 752 event record count = 13)
12-03 23:55:35.974 14197 14202 I art     : Do full code cache collection, code=123KB, data=88KB
12-03 23:55:35.975 14197 14202 I art     : Starting a blocking GC JitCodeCache
12-03 23:55:35.975 14197 14202 I art     : After code cache collection, code=101KB, data=68KB
12-03 23:55:36.041 14197 14225 I net.syncthing.a.a.h: received index message event, preparing (queued records = 765 event record count = 25)
12-03 23:55:36.079   629   643 I ActivityManager: Waited long enough for: ServiceRecord{b430264 u0 com.renard.ocr/com.google.firebase.iid.FirebaseInstanceIdService}
12-03 23:55:36.177 14197 14225 I net.syncthing.a.a.h: received index message event, preparing (queued records = 790 event record count = 43)
12-03 23:55:36.337 14197 14225 I net.syncthing.a.a.h: received index message event, preparing (queued records = 833 event record count = 595)
12-03 23:55:36.463 14197 14225 I net.syncthing.a.a.h: received index message event, preparing (queued records = 1428 event record count = 634)
12-03 23:55:36.572  6373  6373 D wpa_supplicant: wlan0: Control interface command 'SIGNAL_POLL'
12-03 23:55:37.314 14197 14244 E ExecutorService: java.lang.IllegalArgumentException: provided path is invalid
12-03 23:55:37.314 14197 14244 E ExecutorService:  at net.syncthing.a.c.e.d.l(PathUtils.kt:50)
12-03 23:55:37.314 14197 14244 E ExecutorService:  at net.syncthing.a.c.e.d.d(PathUtils.kt:84)
12-03 23:55:37.314 14197 14244 E ExecutorService:  at net.syncthing.a.c.a.f.<init>(FileInfo.kt:40)
12-03 23:55:37.314 14197 14244 E ExecutorService:  at net.syncthing.a.c.a.f$a.d(FileInfo.kt:163)
12-03 23:55:37.314 14197 14244 E ExecutorService:  at net.syncthing.a.a.h.a(IndexHandler.kt:169)
12-03 23:55:37.314 14197 14244 E ExecutorService:  at net.syncthing.a.a.h$b$a.a(IndexHandler.kt:405)
12-03 23:55:37.314 14197 14244 E ExecutorService:  at net.syncthing.a.a.h$b$b.a(IndexHandler.kt:328)
12-03 23:55:37.314 14197 14244 E ExecutorService:  at net.syncthing.a.a.h$b$a.run(IndexHandler.kt:355)
12-03 23:55:37.314 14197 14244 E ExecutorService:  at net.syncthing.a.c.e.b$a.b(ExecutorUtils.kt:32)
12-03 23:55:37.314 14197 14244 E ExecutorService:  at net.syncthing.a.c.e.b$a.a(ExecutorUtils.kt)
12-03 23:55:37.314 14197 14244 E ExecutorService:  at net.syncthing.a.c.e.b$b.call(ExecutorUtils.kt:41)
12-03 23:55:37.314 14197 14244 E ExecutorService:  at java.util.concurrent.FutureTask.run(FutureTask.java:237)
12-03 23:55:37.314 14197 14244 E ExecutorService:  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
12-03 23:55:37.314 14197 14244 E ExecutorService:  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
12-03 23:55:37.314 14197 14244 E ExecutorService:  at java.lang.Thread.run(Thread.java:761)
12-03 23:55:37.316 14197 14244 I art     : System.exit called, status: 1
12-03 23:55:37.316 14197 14244 I AndroidRuntime: VM exiting with result code 1, cleanup skipped.
12-03 23:55:37.394   629   754 W InputDispatcher: channel '85f8c73 net.syncthing.lite/net.syncthing.lite.activities.MainActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
12-03 23:55:37.394   629   754 E InputDispatcher: channel '85f8c73 net.syncthing.lite/net.syncthing.lite.activities.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
12-03 23:55:37.395   629  1599 D GraphicsStats: Buffer count: 16
12-03 23:55:37.395   629  1594 I WindowManager: WIN DEATH: Window{85f8c73 u0 net.syncthing.lite/net.syncthing.lite.activities.MainActivity}
12-03 23:55:37.395   629  1594 W InputDispatcher: Attempted to unregister already unregistered input channel '85f8c73 net.syncthing.lite/net.syncthing.lite.activities.MainActivity (server)'
12-03 23:55:37.399   629  1599 I ActivityManager: Process net.syncthing.lite (pid 14197) has died
12-03 23:55:37.399   629  1599 D ActivityManager: cleanUpApplicationRecord -- 14197
12-03 23:55:37.400   629  1599 W ActivityManager: Force removing ActivityRecord{380370b u0 net.syncthing.lite/.activities.MainActivity t14057}: app died, no saved state
12-03 23:55:37.407   299   299 I Zygote  : Process 14197 exited cleanly (1)
`

**Comment by l-jonas** [comment]
@Newar417 Yes, it helps. I created <https://github.com/syncthing/syncthing-lite/issues/106> for the first exception in it. The second exception (java.lang.IllegalArgumentException: provided path is invalid) is not usable yet. With the new version 0.3.6, there is a setting for detailed errors which - when enabled - should include the file name of the file which causes this exception.

**Comment by Pazuu** [comment]
With version 0.3.7 i can add a device and establish a connection. The crash is gone and the device shows up in the list. Thanks!!! :smiley_cat:

**Comment by l-jonas** [comment]
@yeus Does it work for you too now?
@Newar417 If you still get "provided path is invalid" then please enable the detailed errors and create a new issue.

**Comment by Newar417** [comment]
F-Droid only updated to 0.3.7 yesterday.
I can see my device ID, devices, folders, but not files. It still crashes after a little while. The basic crash reporter also works now. As you can see it is still there, will create the issue: 
```Version: 0.3.7
java.lang.IllegalArgumentException: provided path is invalid
	at net.syncthing.a.c.e.c.l(PathUtils.kt:50)
	at net.syncthing.a.c.e.c.d(PathUtils.kt:84)
	at net.syncthing.a.c.a.f.<init>(FileInfo.kt:40)
	at net.syncthing.a.c.a.f$a.d(FileInfo.kt:163)
	at net.syncthing.a.a.c.b.a(IndexElementProcessor.kt:109)
	at net.syncthing.a.a.c.b.a(IndexElementProcessor.kt:33)
	at net.syncthing.a.a.c.e.a(IndexMessageProcessor.kt:27)
	at net.syncthing.a.a.c.f$e.a(IndexMessageQueueProcessor.kt:116)
	at net.syncthing.a.a.c.f$e.a(IndexMessageQueueProcessor.kt:35)
	at net.syncthing.repository.android.a$a.call(SqliteIndexRepository.kt:24)
	at android.arch.b.b.e.a(RoomDatabase.java:303)
	at net.syncthing.repository.android.a.a(SqliteIndexRepository.kt:15)
	at net.syncthing.a.a.c.f.a(IndexMessageQueueProcessor.kt:111)
	at net.syncthing.a.a.c.f$1.c_(IndexMessageQueueProcessor.kt:86)
	at a.c.b.a.a.b(ContinuationImpl.kt:32)
	at kotlinx.coroutines.az$a.a(Dispatched.kt:235)
	at kotlinx.coroutines.a.run(AbstractContinuation.kt:19)
	at kotlinx.coroutines.c.i.run(Tasks.kt:94)
	at kotlinx.coroutines.c.a.a(CoroutineScheduler.kt:586)
	at kotlinx.coroutines.c.a.a(CoroutineScheduler.kt:60)
	at kotlinx.coroutines.c.a$b.run(CoroutineScheduler.kt:732)

java.lang.IllegalArgumentException: provided path is invalid
	at net.syncthing.a.c.e.c.l(PathUtils.kt:50)
	at net.syncthing.a.c.e.c.d(PathUtils.kt:84)
	at net.syncthing.a.c.a.f.<init>(FileInfo.kt:40)
	at net.syncthing.a.c.a.f$a.d(FileInfo.kt:163)
	at net.syncthing.a.a.c.b.a(IndexElementProcessor.kt:109)
	at net.syncthing.a.a.c.b.a(IndexElementProcessor.kt:33)
	at net.syncthing.a.a.c.e.a(IndexMessageProcessor.kt:27)
	at net.syncthing.a.a.c.f$e.a(IndexMessageQueueProcessor.kt:116)
	at net.syncthing.a.a.c.f$e.a(IndexMessageQueueProcessor.kt:35)
	at net.syncthing.repository.android.a$a.call(SqliteIndexRepository.kt:24)
	at android.arch.b.b.e.a(RoomDatabase.java:303)
	at net.syncthing.repository.android.a.a(SqliteIndexRepository.kt:15)
	at net.synct```

**Comment by l-jonas** [comment]
The first issue (as described at the first post and at <https://github.com/syncthing/syncthing-lite/issues/98#issuecomment-443741712>) is fixed now. For the second one, there is <https://github.com/syncthing/syncthing-lite/issues/121>. Due to that, this is closed now.
